name: "CI: make"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install toolchain
        run: sudo apt-get install gcc-arm-embedded
      - name: Build
        run: make
