#ifndef FEATURES_H
#define FEATURES_H

#define ENABLE_WEBSERIAL
// #define ENABLE_SYNC
#define ENABLE_RPM_CALC
// #define ENABLE_CPWM_IT
#define ENABLE_INTERRUPTS

#define ENABLE_DEBUG_SETUP
#define ENABLE_DEBUG_LOOP
#define ENABLE_TRACE

#define ENABLE_IGNITION
// #define ENABLE_INJECTION
#define ENABLE_SENSORS
#define ENABLE_MEMORY
#define ENABLE_PMIC

#define ENABLE_US_TIM

// #define ENABLE_ENGINE_FRONTEND

#define ENABLE_CAN_ISO_TP

#endif