// OpenEFI libs:
#include "aliases/memory.hpp"
#include "efi_config.hpp"
#include "cpwm/cpwm.hpp"
#include "cpwm/rpm_calc.h"
#include "debug/debug_local.h"
#include "engine/engine.hpp"
#include "ignition/include/ignition.hpp"
#include "injection/injection.hpp"
#include "pmic/pmic.hpp"
#include "sensors/sensors.hpp"
#include "usbd_cdc_if.h"
#include "webserial/commands.hpp"
#include "engine_status.hpp"