name: DOCS

on:
  push:
    branches: [master]

jobs:
  docs:
    name: docs
    runs-on: "ubuntu-latest"
    container:
        image: ghcr.io/churrosoft/openefi_docker:main
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
    steps:
      - uses: actions/checkout@v3

      - name: Build docs
        env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          chmod +x ./gen_doc.sh
          ./gen_doc.sh "$GH_REPO_TOKEN"

      - uses: actions/upload-artifact@v3
        name: Upload docs to artifacts
        with:
          name: artifacts
          path: ./
